CREATE USER IF NOT EXISTS 'Aula'@'%' IDENTIFIED BY 'Aula';

CREATE DATABASE IF NOT EXISTS Aula;

ALTER DATABASE Aula
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON Aula.* TO 'Aula'@'%' IDENTIFIED BY 'Aula';
